# Layer 0 -> any compatible configuration-management tool. After a checked
# apply, scripts/deploy-layer0.ps1 writes out/ansible-inventory.ini,
# out/nodes.json and out/network.json (git-ignored) in this directory.
# Consumers copy them into their own configuration; this module never writes
# into another directory.

locals {
  control_plane = { for name, n in local.nodes : name => n if n.role == "control-plane" }
  workers       = { for name, n in local.nodes : name => n if n.role == "worker" }

  inventory = {
    all = {
      vars = {
        ansible_user = var.admin_user
      }
      children = {
        rke2_server = {
          hosts = { for name, n in local.control_plane : name => { ansible_host = n.ipv4 } }
        }
        rke2_agent = {
          hosts = { for name, n in local.workers : name => { ansible_host = n.ipv4 } }
        }
        rke2_cluster = {
          children = { rke2_server = {}, rke2_agent = {} }
        }
      }
    }
  }

  # The same inventory in INI form (groups rke2_server, rke2_agent, rke2_cluster).
  inventory_ini = join("\n", concat(
    [
      "# Generated by standalone Hyper-V Layer 0 (tofu output -raw ansible_inventory_ini).",
      "",
      "[rke2_server]",
    ],
    [for name in sort(keys(local.control_plane)) : "${name} ansible_host=${local.control_plane[name].ipv4}"],
    ["", "[rke2_agent]"],
    [for name in sort(keys(local.workers)) : "${name} ansible_host=${local.workers[name].ipv4}"],
    [
      "",
      "[rke2_cluster:children]",
      "rke2_server",
      "rke2_agent",
      "",
      "[rke2_cluster:vars]",
      "ansible_user=${var.admin_user}",
      "ansible_python_interpreter=/usr/bin/python3",
      "",
    ],
  ))
}

output "nodes" {
  description = "Every VM: role, IPv4, MAC, sizing, Hyper-V VM name."
  value = {
    for name, n in local.nodes : name => {
      vm_name      = hyperv_vm.vm[name].name
      role         = n.role
      ipv4         = n.ipv4
      mac          = n.mac_upper
      cpus         = n.cpus
      memory_mb    = n.memory_mb
      data_disk_gb = n.data_disk_gb
    }
  }
}

output "nodes_json" {
  description = "Same as `nodes`, as a JSON string (tofu output -raw nodes_json)."
  value = jsonencode({
    for name, n in local.nodes : name => {
      role = n.role
      ipv4 = n.ipv4
      mac  = n.mac_upper
    }
  })
}

output "control_plane_ips" {
  description = "IPv4 addresses of the control-plane nodes."
  value       = [for n in values(local.control_plane) : n.ipv4]
}

output "worker_ips" {
  description = "IPv4 addresses of the worker nodes."
  value       = [for n in values(local.workers) : n.ipv4]
}

output "ansible_inventory_ini" {
  description = "Ansible INI inventory (groups rke2_server / rke2_agent / rke2_cluster) for Layer 1's inventory/hosts.ini."
  value       = local.inventory_ini
}

output "ansible_inventory" {
  description = "The same inventory as YAML (groups rke2_server / rke2_agent / rke2_cluster)."
  value       = yamlencode(local.inventory)
}

output "ansible_inventory_json" {
  description = "The same inventory as JSON (Ansible also accepts this as an inventory file)."
  value       = jsonencode(local.inventory)
}

output "network" {
  description = "The VM network, for Layer 2 settings such as the kube-vip LoadBalancer pool."
  value = {
    cidr        = var.network.cidr
    gateway     = var.network.gateway
    dns_servers = var.network.dns_servers
    switch_name = var.switch_name
  }
}
